### PR TITLE
Update aws-cli to most recent version

### PR DESCRIPTION
**Pull request by gkrizek**
The `aws-cli` in all containers is starting to get out of date. I think it's time to update all of them to the latest version as of writing.

This is specifically a problem with the `docker/1.12.1` image. It doesn't support the `--no-include-email` flag when trying to login. This will start to become a problem as people try to migrate their `buildspec.yml` files to a future-proof state.

https://docs.docker.com/engine/deprecated/#e-and---email-flags-on-docker-login
https://github.com/aws/aws-cli/issues/1926

### CODE REVIEW

**Comment by gkrizek** [comment]
This repo doesn't really seem to be maintained. I can't use any of the AWS provided images because the CLI is too far behind.  Would love to see these get updated.

**Comment by jvusich** [comment]
Apologies for the delay, and thanks for the PR! Marking this for review/merge in our next curated image release cycle.

**Comment by gkrizek** [comment]
@jvusich Thanks for the reply! That sounds great, and would be very helpful.

**Comment by gkrizek** [comment]
I updated the CLI version once more to support the `aws codepipeline list-pipeline-executions` command released in version 1.11.111 I believe. This command is _very_ helpful if you are using CodeBuild with CodePipeline.

**Comment by subinataws** [comment]
aws-cli has been updated to a more recent version (aws-cli/1.14.3).

Marking this resolved.

**Pull request closed without merging**
