### PR TITLE
Add support for PHP 7.1

### PR DESCRIPTION
**Pull request by rdehnhardt**
*Issue #53 

*Description of changes: Add suport for PHP 7.1 with a PHP 7.1.16 Version

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by whera** [comment]
Great! Will be very useful

**Comment by clareliguori** [comment]
Thanks @rdehnhardt! Can you rebase against latest? There are some fixes for PHP composer that have been pushed.

Can you also provide details about how you tested this image?  For example, you can use the [new local build agent](https://github.com/aws/aws-codebuild-docker-images/tree/master/local_builds) to run the image against a repo that requires PHP 7.1.

**Comment by rdehnhardt** [comment]
@clareliguori 

I solve the conflicts and test in my project with my custom AWS CodeBuild in AWS CodePipeline

**Comment by clareliguori** [comment]
Please remove all changes to PHP 5.6 and 7.0 images. It looks like it's accidentally reverting some of the recent changes to those files.  Let's keep this PR specific to 7.1

**Comment by rdehnhardt** [comment]
Yes, no problem, I rebase to upstream master and add just 7.1 features

**Comment by eNzyOfficial** [comment]
Any update on this?

**Comment by rdehnhardt** [comment]
Wait for approval

**Comment by clareliguori** [comment]
Sorry for the delay here.  Dockerfile looks good to me!  Because this is a brand-new image, there is some work that needs to happen behind the scenes to get this released on CodeBuild.  This PR will get merged once we're able to get that work scheduled and completed.

**Comment by rdehnhardt** [comment]
Hello @clareliguori, several weeks have already passed since the last interaction, do you have some information about this image?

**Comment by rdehnhardt** [comment]
I already gave up

**Comment by ilgityildirim** [comment]
I wish this would be released sooner. I mean PHP 7.0 is quite old by now. However we can still use docker images.

**Comment by johnhanks1** [comment]
This is now available on our console. Thanks for the contribution.

https://github.com/aws/aws-codebuild-docker-images/releases/tag/1.7.0.0

**Pull request closed without merging**
