### PR TITLE
Update Go minior releases

### PR DESCRIPTION
**Pull request by nc-wittj**
*Issue #, if available:*

*Description of changes:*
New minor versions of Go have been released (including security patches and bug fixes). This PR updates to the latest minor version for both the `standard:3.0` and the `standard:4.0` images.

For the `standard:3.0` image:
 - `1.13.4` -> `1.13.9`
 - `1.12.13` -> `1.12.17`

For the `standard:4.0` image:
 - `1.13.8` -> `1.13.9`
 - `1.14.0` -> `1.14.1`

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by nc-wittj** [comment]
Looks like we're blocked by https://github.com/syndbg/goenv/pull/116 for the `standard:4.0` image.

**Comment by syndbg** [comment]
Sorry, merged :)

**Comment by nc-wittj** [comment]
Thanks, @syndbg! I think this PR should be good to go then! I seem to be able to build both containers locally.

**Comment by subinataws** [comment]
Thanks for the contribution. We will pick this update in our next release.

**Comment by nc-wittj** [comment]
@subinataws Thanks! This PR is now outdated. We should upgrade to Go 1.14.2 and Go 1.13.10.

**Comment by subinataws** [comment]
Just to set expectations, our release starts from an internal version of the Dockerfile and we push that updated Dockerfile to thin repo as the last step of the release. While you can update your PR here, note that isn't what necessarily get picked up internally. We have a release in flight which has 1.14.2 and 1.13.10 in it already. It'll take a few weeks to become user visible as it needs to roll out to all AWS Regions.

**Comment by nc-wittj** [comment]
@srikanthataws Ah, thanks for the clarification! Should we keep this PR open if that's already in flight?

**Comment by subinataws** [comment]
Resolving this. This update is in flight.

**Pull request closed without merging**
