### PR TITLE
Add Docker buildx tool to al2/aarch64/standard:3.0

### PR DESCRIPTION
**Pull request by i4M1k0SU**
*Issue #, if available:* #640

*Description of changes:*
Add docker-buildx binary, which has been removed from docker-cli in 23.0.0

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by i4M1k0SU** [comment]
Changed to use `/usr/local/lib/docker/cli-plugins` dir, including docker-compose.

**Comment by doowonee** [comment]
Any progress? I really need this feature! Any reviewers?

**Comment by nlsteers** [comment]
bumping, we'd also really like this feature!

**Comment by rjdsgomes** [comment]
Also here, bumped in the same issue 🤔

**Comment by PedroMiguelFMoreira** [comment]
Same as all the above. 😢

**Comment by ajsousas** [comment]
Had the same issue :(

**Comment by Dylan-AWS** [comment]
This is no longer needed after #697 697

**Pull request closed without merging**
