### PR TITLE
updating PHP to latest 8.0.16

### PR DESCRIPTION
**Pull request by AdamWills**
*Issue #, if available:* https://github.com/aws/aws-codebuild-docker-images/issues/506

*Description of changes:*
This PR updates the patch version of PHP 8.0.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by MajorasJack** [comment]
+1

**Comment by khimananda-c2** [comment]
+1

**Comment by khimananda** [comment]
+1

**Comment by mohammad-pouri** [comment]
@leoherran-aws please please please consider this.

**Comment by Dylan-AWS** [comment]
We have updated to PHP 8.0.18 in #535. Thanks for submitting. Closing this pr.

**Pull request closed without merging**
