### PR TITLE
Add Support for Java Open JDK 11

### PR DESCRIPTION
**Pull request by t04glovern**
*Issue #138*

*Description of changes:*

Support for OpenJDK 11 added in this pull request. I followed the base version used for the previous LTS java release and included steps for setting up [Java 11 from the offical sources](https://jdk.java.net/11/).

The biggest change from java 9 is the way versions are tagged in Java 11. I've replaced the path hash (that was used for Java 9) with a `JDK_VERSION_TAG` parameter that denotes version on-top of the base JDK version to use.

I've tested this workflow in ECR on a number of Java 11 projects I have and haven't run into problems in during my adventures so far.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by johnhanks1** [comment]
Could you point me to some open source packages that you used for testing of this image?

**Comment by teimatinimarin** [comment]
Hi @t04glovern, is this image available in DockerHub?

**Comment by t04glovern** [comment]
@johnhanks1 @teimatinimarin both of the packages I used to test are internal to my org, I'll integrate it with [spring-projects/spring-petclinic](https://github.com/spring-projects/spring-petclinic) tonight; however until then if you'd like to access a version of the image, I've hosted it on my DockerHub

https://hub.docker.com/r/t04glovern/codebuild-openjdk-11/

**Comment by t04glovern** [comment]
Hi guys,

I've put together a demo repo that outlines what you need to do in order to build a java11 application with CodeBuild then have it push to ECR.

https://github.com/t04glovern/employee-springboot-sample

I've added screenshots of the configuration settings you need to use in CodeBuild, however most of those should be self-explanatory. The important bit is the definition of the java docker image `t04glovern/codebuild-openjdk-11`

**Comment by jocelynthode** [comment]
We also tested it on internal images and it works great. Hope this will be added to default AWS images soon :)

**Comment by subinataws** [comment]
Thanks for the contribution. We'll get this version supported in an upcoming release.

**Comment by johnhanks1** [comment]
This is now available on our console. Thanks for the contribution. 

https://github.com/aws/aws-codebuild-docker-images/releases/tag/1.7.0.0

**Pull request closed without merging**
