### PR TITLE
Add Go image with Go v1.11

### PR DESCRIPTION
**Pull request by brunetto**
Add aws-codebuild-docker-images/ubuntu/golang image with Go v1.11

### CODE REVIEW

**Comment by subinataws** [comment]
@brunetto - Thanks for the contribution. We have this version update in the works internally. We will be rolling with that update instead. No ETAs to share on when it'll be available, but it will be queued up for next batch of updates.

**Comment by brunetto** [comment]
@subinataws We are eager to see this update!! 😄 
It would improve out pipelines a lot!!

**Comment by MattMasters** [comment]
Hey 👋  @subinataws, has their been any movement on this?

**Comment by subinataws** [comment]
In a few weeks. Thanks for checking in. If you are blocked, while not ideal, you consider using a custom image for Go 1.11 to unblock your builds on CodeBuild.

**Comment by subinataws** [comment]
We hope to update Go 1.11 in the next few weeks. If you are blocked, please consider using a custom Docker image as your build environment on CodeBuild.

**Comment by subinataws** [comment]
Added this support in https://github.com/aws/aws-codebuild-docker-images/releases/tag/1.7.0.0

**Comment by johnhanks1** [comment]
This is now available on our console. Thanks for the contribution.

https://github.com/aws/aws-codebuild-docker-images/releases/tag/1.7.0.0

**Pull request closed without merging**
