### PR TITLE
standard:5.0 Golang version 1.16 support and bump to 1.15.12

### LINKED ISSUE #425: Add support for Go 1.16
Since Go 1.16 was released, I would love to have this available in the Codebuild images.

Blog Post:
https://blog.golang.org/go1.16

### PR DESCRIPTION
**Pull request by dougnukem**
*Issue #, if available:* closes #425

*Description of changes:*
`aws/codebuild/standard:5.0` image changes
- Add support for `golang: 1.16`
- Bump go 1.15 to latest version `1.15.12`

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by guusvw — APPROVED** [review]

**Comment by guusvw** [comment]
Any plans when to merge it? =D 
I would be super happy to get Go 1.16 in the image

**Comment by dougnukem** [comment]
> Any plans when to merge it? =D
> I would be super happy to get Go 1.16 in the image


@guusvw I'm not sure the best way to get this in front of the repo reviewers/maintainers (also not sure if they push from an internal repo when updating runtime changes etc). Maybe @subinataws could clarify if this is the correct process for bumping the go runtime version.

**Comment by subinataws** [comment]
@dougnukem - The runtime images are indeed updated from an internal repo. Once that's updated, this repo is synced.

**Comment by dougnukem** [comment]
@guusvw as a temporary work around until the go runtime image is updated from the internal repo you can use my fork.

https://hub.docker.com/repository/docker/dougnukem/aws-codebuild-standard

```
dougnukem/aws-codebuild-standard:5.0
```

**Review by leoherran-aws — APPROVED** [review]

**Comment by leoherran-aws** [comment]
Thanks for your contribution! We are building this change into our next release. I'll update here when the standard:5.0 image has a new version published.

**Comment by leoherran-aws** [comment]
New curated images are live: https://github.com/aws/aws-codebuild-docker-images/releases/tag/21.08.20

**Pull request merged**
