### PR TITLE
Update runtimes.yml

### PR DESCRIPTION
**Pull request by matsev**
Correct copy / paste error

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by subinataws** [comment]
@matsev - Thanks for the contribution. Docker version will always be the tip version and does not need to be specified in the runtime-versions of the buildspec any more. Unlike other programming language runtimes, simply enabling the "privileged" mode on the CodeBuild Project will enable Docker access inside the build container.

**Comment by matsev** [comment]
@subinataws Sounds good, however then I don't understand the Docker version declarations on [line 113](https://github.com/aws/aws-codebuild-docker-images/blob/master/ubuntu/standard/4.0/runtimes.yml#L113) and [line 116](https://github.com/aws/aws-codebuild-docker-images/blob/master/ubuntu/standard/4.0/runtimes.yml#L116) respectively?

This PR simply aligns the output of the Docker version in the `echo` command on [line 115](https://github.com/aws/aws-codebuild-docker-images/blob/master/ubuntu/standard/4.0/runtimes.yml#L115) (currently `19`) so that it matches the declared version on [line 113](https://github.com/aws/aws-codebuild-docker-images/blob/master/ubuntu/standard/4.0/runtimes.yml#L113) (currently `18`).

**Comment by subinataws** [comment]
@matsev - The echo statement for both shows Docker 19 as the output, because if you use "docker: 18", "docker: 19", or not declare anything, we always pick just the latest version, which is Docker 19 in standard:4.0. Without having support for "docker: 18" in runtimes yaml, customers who may have previously declared that runtimes version would get a build error of unknown runtime. We basically left it there for backwards compatibility. Apologies for the confusion this is causing. With the next version update (e.g.: standard:5.0), we won't be having docker in the runtimes yaml.

**Comment by matsev** [comment]
@subinataws Thanks for the clarification!

**Pull request closed without merging**
