### PR TITLE
Add node14 to aarch64 in AL2:2.0 image

### PR DESCRIPTION
**Pull request by Kaas59**
*Issue #528*

*Description of changes:Added Node14 to Aarch64 version of AL2: 2.0*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by Kaas59** [comment]
@skilbjo Thanks for the suggestion!
I’ll try this PR for node@16 for AL2.0 along with updating to the new minor version on node@14!

**Comment by purplexed** [comment]
Thank you for looking into it @Kaas59 ! Looks like ARM images are being left behind despite all efforts to try and use that architecture more by AWS.

**Comment by radekwielonski** [comment]
Hi! Is there any news on this PR? When can we expect it to be merged?

**Comment by Dylan-AWS** [comment]
Added support for Node18 in arm with [23.04.25](https://github.com/aws/aws-codebuild-docker-images/releases/tag/23.04.25)

**Pull request closed without merging**
