### PR TITLE
Add .NET 5.0, 6.0 to Amazon Linux 2 x86-64 image

### PR DESCRIPTION
**Pull request by cdonnellytx**
*Issue #, if available:*
N/A

*Description of changes:*

.NET upgrades for parity with aws/codebuild/standard:5.0 image.

- 3.1: patch ~404~ 419
- 5.0
- 6.0 (see #498)

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by snoworc — APPROVED** [review]

**Review by HudsonAkridge — APPROVED** [review]
LGTM, and something needed by our group as well

**Review by say25 — APPROVED** [review]
PLZ Merge

**Review by HardBlock729 — APPROVED** [review]

**Comment by snoworc** [comment]
#497 also related

**Review by Vitaliy-Mishur — APPROVED** [review]

**Review by hasanmanzak — APPROVED** [review]
Straight forward enough..

**Review by fmendoza-pf — APPROVED** [review]

**Comment by HudsonAkridge** [comment]
@leoherran-aws , could you help us understand what the next steps are to getting this merged in please?

Our group also opened up an AWS support ticket a while back to request this be merged in and was told that the AWS team that supports Codebuild was made aware of the PR and would merge it in as soon as they were able.

Could we get an ETA of that please? The delay is causing some exceptional workarounds, such as: Our team has shifted one project over to Github Actions and custom Docker Images to pull us off Codebuild completely.

Thank you!

**Comment by leoherran-aws** [comment]
I cannot provide an ETA but the release process is in progress and we will update this ticket when it's complete.

**Comment by bryantqo** [comment]
Looking at the changes everything looks ok as far as I know. The only thing I would be concerned about is including dotnet5 as it is EOL on May 8, 2022

**Comment by snoworc** [comment]
> Looking at the changes everything looks ok as far as I know. The only thing I would be concerned about is including dotnet5 as it is EOS on May 8, 2022

@bryantqo fair enough. However, this code does (did) have latest master merged in it. Whenever 5.0 support gets dropped from the current version, we can merge master again.

**Comment by mayankbigm** [comment]
Can we please get this merged. We are waiting for .Net 6 runtime for AWS Codebuild

**Review by mayankbigm — APPROVED** [review]

**Comment by mayankbigm** [comment]
Hi @subinataws How are you!
Saw you were able to close some other PR on this repo thus reaching out
Can you or someone who has write access to this , please review and merge this.

Please feel free to tag others with write access. Much appreciated. Thanks

**Review by PeterSHL — APPROVED** [review]

**Review by adam-bentley — APPROVED** [review]

**Comment by benwolfpredictile** [comment]
Seriously, .Net 3.1 is EOS in a few months. Can we get some official support for .Net 6? I know I can run scripts to install this myself, but that is sort of counter to the point of the CodeBuild/CodePipeline managed services. If I wanted to build my own images I would not use CodeBuild. This is getting really late in the process. In a few months, .Net 6 will be the only supported .Net version available, yet there's no support here.

**Comment by fmendoza-pf** [comment]
> 

I would also add that unless I'm mistaken this aws-codebuild-docker is not open source. We're paying for it.

**Comment by cdonnellytx** [comment]
I've resolved the conflict due to the patch version updated on master.  I also updated to 5.0.408 (again, to match the other image) and to 6.0.301.

**Comment by subinataws** [comment]
.net 6 is now supported in https://github.com/aws/aws-codebuild-docker-images/releases/tag/22.06.30

**Pull request closed without merging**
